### ISSUE TITLE
Cannot find module 'handlebars'

### ISSUE THREAD

**Issue by mossonli** [aleen42/gitbook-footer#13]
mac 
gitbook install   success
git serve
....
PluginError: Error with plugin "page-footer": Cannot find module 'handlebars'
Require stack:
- /Users/mosson/Documents/gitbook/node_modules/gitbook-plugin-page-footer/lib/index.js
- /Users/mosson/.gitbook/versions/3.2.3/lib/plugins/loadPlugin.js
- /Users/mosson/.gitbook/versions/3.2.3/lib/plugins/loadForBook.js
- /Users/mosson/.gitbook/versions/3.2.3/lib/plugins/index.js
- /Users/mosson/.gitbook/versions/3.2.3/lib/api/encodeGlobal.js
- /Users/mosson/.gitbook/versions/3.2.3/lib/api/index.js
- /Users/mosson/.gitbook/versions/3.2.3/lib/output/getModifiers.js
- /Users/mosson/.gitbook/versions/3.2.3/lib/output/json/onPage.js
- /Users/mosson/.gitbook/versions/3.2.3/lib/output/json/index.js
- /Users/mosson/.gitbook/versions/3.2.3/lib/output/index.js
- /Users/mosson/.gitbook/versions/3.2.3/lib/index.js
- /usr/local/lib/node_modules/gitbook-cli/lib/local.js
- /usr/local/lib/node_modules/gitbook-cli/lib/index.js
- /usr/local/lib/node_modules/gitbook-cli/bin/gitbook.js

**Comment by aleen42** [comment]
Sorry for the late answer, and try to upgrade to `5.4.9` to fix the dependency problem.
