### ISSUE TITLE
What is the time to modify?

### ISSUE THREAD

**Issue by zq99299** [aleen42/gitbook-footer#8]
修改时间取的是什么时间？
What time does it take?

modified at 2016-12-17 00:17:53

当前md文件的最后修改日期吗？
Is the last modification date for the current MD file?

我这里是中国时间，但是最终显示的时间和我的md文件修改时间不一致呢？差很多
I am here China time, but the final display time and my MD file modification time inconsistent? Much worse

比如：
正确的应该是：2016-12-16 16:17:53
但是该插件显示： 2016-12-17 00:17:53

For example:
Correct should be: 2016-12-16 16:17:53
But the plugin shows: 2016-12-17 00:17:53

**Comment by aleen42** [comment]
utcOffset 传参，修改一下时区。

**Comment by zq99299** [comment]
你是中国人还是外国人。 我还翻译成英文。  - -

**Comment by aleen42** [comment]
中國來著

**Comment by zq99299** [comment]
北京时间 对应的是几？

**Comment by aleen42** [comment]
8，試一下

**Comment by zq99299** [comment]
你的默认参数就是8

**Comment by zq99299** [comment]
"format": "yyyy-MM-dd hh:mm:ss",
hh 是不是应该是大写？ 但是我用大写的话。 就直接不替换了

**Comment by aleen42** [comment]
你的utcOffset传0吧

**Comment by aleen42** [comment]
对照一下 https://github.com/aleen42/PersonalWiki/blob/master/book.json#L67 现在时区应该是准的
